<?xml version="1.0"?>
<!--This is a draft spec for ERNIE seedsets in xml format with an internal DTD -->
<!--This format is used for gen1 seedsets for network construction in ERNIE case studies-->
<!--Author: George Chacko-->
<!--Date: 12/01/2017-->
<!DOCTYPE case_study [
<!ELEMENT case_study (therapeutic | diagnostic | intervention)>
<!ELEMENT therapeutic (fda , pubmed , ct , patent)>
<!ELEMENT fda (active_ingredient , brand_name , (nda | bla)* , approval_date , source , medical_review_pmid* , fda_other_pmid*)>
<!ELEMENT active_ingredient (#PCDATA)>
<!ELEMENT brand_name (#PCDATA)>
<!ELEMENT nda (#PCDATA)>
<!ELEMENT bla (#PCDATA)>
<!ELEMENT approval_date (#PCDATA)>
<!ELEMENT source (#PCDATA)>
<!ELEMENT medical_review_pmid (#PCDATA)>
<!ELEMENT fda_other_pmid (#PCDATA)>
<!ELEMENT pubmed (pubmed_preapp_pmid)+>
<!ELEMENT pubmed_preapp_pmid (#PCDATA)>
<!ELEMENT ct (ct_preapp_reference_pmid* , ct_preapp_publication_pmid*)>
<!ELEMENT ct_preapp_reference_pmid (#PCDATA)>
<!ELEMENT ct_preapp_publication_pmid (#PCDATA)>
<!ELEMENT ct_preapp_nct (#PCDATA)>
<!ELEMENT ct_postapp_nct (#PCDATA)>
<!ELEMENT patent (npl_pmid* , pl_USpatentno*)>
<!ELEMENT npl_pmid (#PCDATA)>
<!ELEMENT pl_USpatentno (#PCDATA)>
]>
<drug>
  <fda>
    <active_ingredient>naltrexone</active_ingredient>
    <brand_name>Revia</brand_name>
    <brand_name>Vivitrol</brand_name>
    <nda>18932</nda>
    <nda>21897</nda>
    <approval_date>11/20/1984</approval_date>
    <approval_date>04/13/2006</approval_date>
    <source>drugs@fda</source>
    <naltrexone_fda_medical_review_pmid>00000</naltrexone_fda_medical_review_pmid>
    <naltrexone_fda_other_pmid>1259230</naltrexone_fda_other_pmid>
  </fda>
  <patent>
    <patent_pl_USPatentno>US3332950A</patent_pl_USPatentno>
    <naltrexone_npl_pmid>00000</naltrexone_npl_pmid>
  </patent>
  <ct>
    <ct_preapp_reference_pmid>00000</ct_preapp_reference_pmid>
    <ct_preapp_publication_pmid>00000</ct_preapp_publication_pmid>
  </ct>
  <pubmed>
    <pubmed_preapp_pmid>3000805</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>24271122</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>4084183</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>4080766</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>4080758</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>4080100</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>4057080</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>4057078</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>4057071</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>3002317</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>3001233</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2997432</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2935140</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2934749</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2934748</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2867174</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2865892</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2865342</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2998381</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>4054212</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2996912</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>4070418</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>4070326</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>4045722</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>4042525</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>4031019</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>3843301</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>3002205</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2995111</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2995741</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>4052749</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>4033351</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>4033357</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>4064907</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>4063057</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>3901041</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>3002693</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2997887</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2997654</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2993609</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2993589</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2992300</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2864100</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>4043225</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2991684</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2862958</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>4070392</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>4059307</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>3843739</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>3843737</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2997642</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2989428</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2865117</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>4059587</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>4009506</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>3892216</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2992669</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2991795</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2991346</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2409281</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2409280</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2989632</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>4023023</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>4022271</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>4009482</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>3908340</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>3896411</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>3843728</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>3843718</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2993171</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2991949</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2989500</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2867051</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2867050</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>4018136</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>4005545</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>4040246</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2999724</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2985759</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>3990510</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2986002</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2984501</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2859095</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>4039002</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>4011730</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>4000407</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>3991774</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>3983028</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2991678</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2859565</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2578990</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>3986523</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>3991759</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>3991756</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>3979972</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2983171</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>3838691</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>3921389</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>3971145</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>16726000</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>4039802</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>4039067</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>4000410</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>3969057</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>3888577</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>3888575</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2987990</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2987740</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2984700</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2982011</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2860592</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2859972</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2582304</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2984010</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>4067601</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>4047981</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>4041065</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>3991363</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>3981418</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>3936101</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>3931155</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>3927336</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>3923525</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>3923521</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>3916036</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>3914209</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>3908352</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>3903533</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>3891654</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>3832903</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>3007777</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2997824</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2997614</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2986883</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2981129</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2981076</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2869149</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>2412252</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6529627</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6505691</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6543246</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6522309</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6389867</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6209395</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6099514</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6099513</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6099508</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6099494</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6099490</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6099488</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6099471</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6094248</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6092812</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6092373</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6520774</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6488691</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6150815</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6095280</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6092898</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6091150</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6529975</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6541499</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6541122</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6386494</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6150086</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6149142</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6092607</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6090663</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6088697</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6090835</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6482651</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6090834</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6541075</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6499910</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6094203</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6494208</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6469938</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6469937</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6469936</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6469935</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6469934</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6469933</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6469932</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6469931</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6381473</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6206224</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6093153</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6088469</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6088468</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6088467</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6090179</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6540590</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6540199</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6093942</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6087062</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6541225</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6479015</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6429197</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6147336</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6146706</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6146699</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6098896</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6374352</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6329467</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6463075</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6431449</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6328530</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6328153</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6086361</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6328147</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6330479</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6326965</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6326964</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6326963</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6738824</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6737235</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6716270</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6539667</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6473168</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6433331</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6330766</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6330764</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6330761</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6329589</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6326151</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6146106</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6539142</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6722534</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6728879</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6703387</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6091160</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6708723</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6538628</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6324770</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6718461</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6709679</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6709677</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6583447</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6547224</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6486774</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6434974</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6434972</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6325463</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6321146</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6207431</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6148913</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6738790</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6607339</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6424632</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6697193</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6691146</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6321207</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6319931</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6694998</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6543435</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6543398</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6540897</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6524509</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6519154</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6494192</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6475891</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6475888</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6443393</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6443380</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6443377</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6440184</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6436825</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6394130</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6388274</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6388273</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6323369</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6319107</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6151208</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6141278</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6100022</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6099871</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6093484</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6093137</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6084846</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6318895</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6316064</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6668313</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6662195</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6670857</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6665302</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6657726</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6655565</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6315775</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6313736</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6197313</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6419179</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6667710</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6363990</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6321203</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6640516</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6637740</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6320316</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6640302</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6686142</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6653389</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6646353</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6629966</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6619824</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6316371</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6314167</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6312042</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6196793</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6314208</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6310295</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6612331</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6310750</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6313397</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6308767</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6686324</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6634902</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6634889</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6633822</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6359093</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6310111</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6867737</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6881329</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6875851</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6634886</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6634872</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6422028</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6347117</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6309428</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6192235</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6883119</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6883097</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6352139</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6304445</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6884432</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6873180</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6889416</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6136987</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>10317352</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6302425</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6408390</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6308695</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6410281</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6410276</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6410264</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6839176</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6303805</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6338330</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6843792</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6843791</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6682490</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6131119</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6299472</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6299458</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6835979</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6831119</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6682230</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6681633</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6681632</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6308317</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6300933</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6300721</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6296358</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6301847</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6827900</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6843782</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6686696</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6684293</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6678390</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6578730</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6415729</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6408661</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6407041</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6403960</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6322365</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6319928</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6319921</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6319917</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6319914</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6319896</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6319895</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6319887</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6306614</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6296330</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6201940</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6188774</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6184003</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6141501</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6136392</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6135144</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6133288</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6131962</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6129881</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7162354</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6295552</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7143239</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7143233</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6298835</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6298834</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6292396</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6130527</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6130451</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6295778</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6891739</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6129982</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7177344</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7138234</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7131294</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6294686</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6294682</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6290634</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6290184</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7154836</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6296572</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6296567</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6755122</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7181582</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7178183</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7166139</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7145032</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6891063</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6292420</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6291701</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6292636</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6292615</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6183549</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6128656</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6128653</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7145041</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7143556</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6294168</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7100917</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7132574</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6289965</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7089582</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7121747</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6299265</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6291068</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6288945</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6288413</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7108900</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7097642</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6289026</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7109840</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6286325</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7111349</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7111345</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7086683</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7085584</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7045089</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6806253</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7109826</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7047964</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7089032</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7042396</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7042395</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6978757</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6281084</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6176696</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7087676</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6283437</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7061693</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6811941</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6289119</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6280208</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6280206</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6280203</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6121523</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7200037</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7067729</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6203600</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7062259</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6281826</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6278127</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6278126</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6276506</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6121047</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6121045</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6120359</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6277426</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7065829</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7057394</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7037459</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6276546</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6121872</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6122153</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7060629</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7202207</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7171079</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7167863</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7150691</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7122510</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7119946</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7079321</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6961864</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6961861</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6889739</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6817368</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6813889</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6760771</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6760769</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6297359</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6296898</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6291084</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6290924</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6289627</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6281840</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6278352</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7329205</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7185891</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6101080</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7312906</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7297627</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6271598</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6271322</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7300562</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7198791</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6287349</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7284781</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6271561</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7268445</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7318681</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7291246</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7290360</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6765486</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6272086</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6272084</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6266608</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>6272048</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>7297411</pubmed_preapp_pmid>