<?xml version="1.0"?>
<!--This is a draft spec for ERNIE seedsets in xml format with an internal DTD -->
<!--This format is used for gen1 seedsets for network construction in ERNIE case studies-->
<!--Author: George Chacko-->
<!--Date: 12/01/2017-->
<!DOCTYPE case_study [
<!ELEMENT case_study (therapeutic | diagnostic | intervention)>
<!ELEMENT therapeutic (fda , pubmed , ct , patent)>
<!ELEMENT fda (active_ingredient , brand_name , (nda | bla)* , approval_date , source , medical_review_pmid* , fda_other_pmid*)>
<!ELEMENT active_ingredient (#PCDATA)>
<!ELEMENT brand_name (#PCDATA)>
<!ELEMENT nda (#PCDATA)>
<!ELEMENT bla (#PCDATA)>
<!ELEMENT approval_date (#PCDATA)>
<!ELEMENT source (#PCDATA)>
<!ELEMENT medical_review_pmid (#PCDATA)>
<!ELEMENT fda_other_pmid (#PCDATA)>
<!ELEMENT pubmed (pubmed_preapp_pmid)+>
<!ELEMENT pubmed_preapp_pmid (#PCDATA)>
<!ELEMENT ct (ct_preapp_reference_pmid* , ct_preapp_publication_pmid*)>
<!ELEMENT ct_preapp_reference_pmid (#PCDATA)>
<!ELEMENT ct_preapp_publication_pmid (#PCDATA)>
<!ELEMENT ct_preapp_nct (#PCDATA)>
<!ELEMENT ct_postapp_nct (#PCDATA)>
<!ELEMENT patent (npl_pmid* , pl_USpatentno*)>
<!ELEMENT npl_pmid (#PCDATA)>
<!ELEMENT pl_USpatentno (#PCDATA)>
]>
<drug>
  <fda>
    <brand_name>Yervoy</brand_name>
    <active_ingredient>ipilimumab</active_ingredient>
    <bla>125377 </bla>
    <source>drugs@fda</source>
    <ipilimumab_fda_medical_review_pmid>20086001</ipilimumab_fda_medical_review_pmid>
    <ipilimumab_fda_other_pmid>12087419</ipilimumab_fda_other_pmid>
  </fda>
  <patent>
    <pl_USpatentno>US6984720 B1</pl_USpatentno>
    <ipilimumab_npl_pmid>10096554</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>10201965</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>10430624</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>10811122</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>1334116</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>1475190</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>1714933</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>1847722</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>2156778</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>2164219</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>2171783</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>2465550</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>2540528</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>2794510</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>2940206</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>3021470</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>3134293</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>3220103</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>3496540</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>3500211</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>6274961</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>6458039</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>7494109</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>7543139</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>7543510</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>7759881</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>7846057</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>7882171</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>8018598</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>8075633</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>8159246</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>8347558</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>8348148</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>8475122</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>8596936</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>8671638</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>8676074</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>8676075</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>9020839</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>9036940</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>9104819</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>9203422</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>9221747</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>9223321</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>9354465</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>9430233</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>9449722</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>9551948</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>9631000</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>9631008</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>9687526</ipilimumab_npl_pmid>
    <ipilimumab_npl_pmid>9707601</ipilimumab_npl_pmid>
  </patent>
  <ct>
    <ct_preapp_reference_pmid>74375</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>1335362</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>1335364</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>2405271</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>3493433</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>4172540</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>6171553</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>6174490</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>6311878</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>6821816</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>7477169</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>7543139</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>7670677</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>7681997</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>8160096</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>8469286</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>8569196</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>8596936</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>8608507</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>8608507</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>8717514</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>8845294</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>9336134</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>9420067</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>9809728</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>9817276</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>10379968</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>10430624</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>10485649</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>10485649</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>10485649</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>10561185</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>10561349</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>10735499</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>10764421</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>10802351</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>10899916</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>11015443</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>11133760</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>11157024</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>11209085</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>11224527</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>11323285</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>11323675</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>11481353</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>11552950</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>11773176</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>11857337</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>11970966</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>12091876</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>12171950</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>12218188</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>12218188</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>12218188</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>12407406</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>12593621</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>12680791</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>12682289</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>12721664</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>12847138</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>12855568</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>12874215</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>13693470</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>14519751</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>14555498</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>14559843</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>14576661</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>14595408</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>14736927</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>14871849</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>15020614</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>15020614</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>15030777</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>15030777</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>15032581</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>15090449</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>15122199</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>15150081</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>15158627</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>15200998</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>15240681</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>15297412</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>15325032</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>15358536</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>15534492</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>15569934</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>15611321</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>15611998</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>15705911</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>15776005</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>15837746</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>16087865</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>16111570</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>16177953</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>16194701</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>16205727</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>16208700</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>16271509</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>16283570</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>16301685</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>16314647</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>16370382</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>16464564</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>16490844</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>16525185</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>16530813</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>16585157</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>16597592</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>16757720</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>16809739</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>16945766</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>16966688</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>16977338</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>17133440</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>17409927</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>17544497</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>17693134</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>17700621</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>17898045</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>17982122</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>17982122</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>18000991</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>18000991</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>18173375</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>18173375</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>18223165</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>18235113</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>18287062</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>18287062</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>18396195</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>18504926</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>18506026</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>18523152</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>18555546</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>18665147</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>18698040</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>18809614</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>18818309</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>18838703</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>18838703</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>18974373</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>18974373</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>19018089</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>19097774</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>19123898</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>19139439</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>19147765</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>19202079</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>19648604</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>19652578</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>19808874</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>19808874</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>19857783</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>19933915</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>19934295</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>20216240</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>20234320</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>20338627</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>20425606</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>20460488</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>20514052</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>20516446</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>20516446</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>20525992</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>20525992</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>20525992</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>20525992</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>20525992</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>20541055</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>20616954</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>20636812</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>20636812</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>20660832</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>20814764</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>20818862</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>20826737</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>20924130</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>20924130</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>20977700</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>21074057</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>21074057</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>21074064</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>21159637</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>21173711</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>21258248</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>21639810</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>21708958</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>21799510</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>21900389</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>22124104</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>22130161</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>22186141</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>22437870</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>22456429</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>22456429</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>22456429</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>22461641</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>22461641</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>22547592</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>22547592</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>22646630</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>22658127</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>22658128</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>22658128</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>22858559</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>22894884</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>23299197</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>23724867</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>23724867</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>23724867</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>23788581</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>23945592</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>23965900</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>24127452</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>24127452</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>24264989</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>24264989</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>24264990</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>24264990</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>24590637</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>24657498</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>24792872</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>24804867</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>24882670</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>25083336</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>25358689</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>25403209</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>25452452</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>25482239</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>25482239</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>25538176</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>25754329</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>25840693</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>25840693</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>25891173</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>25891304</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>25891304</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>25891304</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>25965370</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>26027431</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>26027431</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>26028255</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>26028255</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>26028407</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>26028407</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>26037795</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>26037795</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>26095785</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>26146806</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>26162965</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>26162965</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>26260659</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>26270858</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>26371143</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>26398076</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>26406148</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>26412456</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>26412456</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>26412456</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>26541606</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>26541606</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>26541610</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>26541610</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>26578451</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>26578451</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>26590773</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>26590773</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>26628942</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>26628942</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>26699946</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>26699946</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>26794930</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>26801886</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>27001570</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>27157491</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>27234989</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>27298410</ct_preapp_reference_pmid>
    <ct_preapp_reference_pmid>27354485</ct_preapp_reference_pmid>
    <ct_publication_pmid>12826605</ct_publication_pmid>
    <ct_publication_pmid>16087944</ct_publication_pmid>
    <ct_publication_pmid>16283570</ct_publication_pmid>
    <ct_publication_pmid>16882708</ct_publication_pmid>
    <ct_publication_pmid>20842054</ct_publication_pmid>
    <ct_publication_pmid>27000274</ct_publication_pmid>
    <ct_publication_pmid>27681753</ct_publication_pmid>
    <ct_publication_pmid>27745820</ct_publication_pmid>
    <ct_publication_pmid>28729151</ct_publication_pmid>
    <ct_publication_pmid>28822576</ct_publication_pmid>
    <ct_publication_pmid>\N</ct_publication_pmid>
  </ct>
  <pubmed>
    <pubmed_preapp_pmid>23226069</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>23049279</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>23037483</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>23024154</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22904648</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22844202</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22778766</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22778760</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22677983</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22666217</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22566975</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22530324</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22477725</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22459268</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22453019</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22453017</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22443134</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22434096</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22432863</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22423265</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22423263</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22419879</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22409862</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22406592</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22402694</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22397654</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22396993</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22396291</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22393198</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22385525</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22385436</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22382362</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22375995</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22370387</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22350184</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22346364</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22339359</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22338019</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22333219</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22326924</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22326922</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22326921</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22306905</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22300855</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22468871</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22271879</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22270215</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22270078</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22267918</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22256820</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22253555</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22231551</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22219590</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22215850</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22209376</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>24451817</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>24451790</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>24451730</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>23788912</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>23788878</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22203769</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22196270</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22193102</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22186141</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22180676</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22146893</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22142824</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22074657</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22130166</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22130164</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22124094</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22123319</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22109345</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22091682</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22082642</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22077981</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22077831</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22071969</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22069060</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22051508</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22047582</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22046181</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22044200</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22036643</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22033581</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22030452</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22028422</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22020206</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22010182</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22006439</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21991906</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21991905</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21991904</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21990407</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21990398</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21957431</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21954698</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21952276</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21951748</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21933959</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21930211</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21917607</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21914583</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21900791</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21900389</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21881038</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21850925</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21843079</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21833591</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21821307</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21815696</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21810572</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21807763</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21806402</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21804596</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21802280</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21788973</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21785279</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21785048</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21777474</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21770473</pubmed_preapp_pmid>