<?xml version="1.0"?>
<!--This is a draft spec for ERNIE seedsets in xml format with an internal DTD -->
<!--This format is used for gen1 seedsets for network construction in ERNIE case studies-->
<!--Author: George Chacko-->
<!--Date: 10/19/2017-->
<!DOCTYPE case_study [
<!ELEMENT case_study (therapeutic | diagnostic | intervention)>
<!ELEMENT therapeutic (fda , pubmed , ct , patent)>
<!ELEMENT fda (active_ingredient , brand_name , (nda | bla)* , approval_date , source , medical_review_pmid* , fda_other_pmid*)>
<!ELEMENT active_ingredient (#PCDATA)>
<!ELEMENT brand_name (#PCDATA)>
<!ELEMENT nda (#PCDATA)>
<!ELEMENT bla (#PCDATA)>
<!ELEMENT approval_date (#PCDATA)>
<!ELEMENT source (#PCDATA)>
<!ELEMENT medical_review_pmid (#PCDATA)>
<!ELEMENT fda_other_pmid (#PCDATA)>
<!ELEMENT pubmed (pubmed_ct_preapp_pmid* , pubmed_ct_postapp_pmid* , pubmed_preapp_pmid+ , pubmed_postapp_pmid+ , pubmed_review_pmid+)>
<!ELEMENT pubmed_ct_preapp_pmid (#PCDATA)>
<!ELEMENT pubmed_ct_postapp_pmid (#PCDATA)>
<!ELEMENT pubmed_preapp_pmid (#PCDATA)>
<!ELEMENT pubmed_postapp_pmid (#PCDATA)>
<!ELEMENT pubmed_reviews_pmid (#PCDATA)>
<!ELEMENT ct (ct_preapp_reference_pmid* , ct_postapp_reference_pmid* , ct_preapp_publication_pmid* , ct_postapp_publication_pmid* , ct_preapp_nct* , ct_postapp_nct*)>
<!ELEMENT ct_preapp_reference_pmid (#PCDATA)>
<!ELEMENT ct_postapp_reference_pmid (#PCDATA)>
<!ELEMENT ct_preapp_publication_pmid (#PCDATA)>
<!ELEMENT ct_postapp_publication_pmid (#PCDATA)>
<!ELEMENT ct_preapp_nct (#PCDATA)>
<!ELEMENT ct_postapp_nct (#PCDATA)>
<!ELEMENT patent (npl_pmid* , pl_USpatentno*)>
<!ELEMENT npl_pmid (#PCDATA)>
<!ELEMENT pl_USpatentno (#PCDATA)>
]>
<drug>
  <fda>
    <active_ingredient>ivacaftor</active_ingredient>
    <brand_name>Kalydeco</brand_name>
    <nda>203188</nda>
    <source>drugs@fda</source>
    <ivacaftor_fda_medical_review_pmid>18442953</ivacaftor_fda_medical_review_pmid>
    <ivacaftor_fda_medical_review_pmid>2475911</ivacaftor_fda_medical_review_pmid>
    <ivacaftor_fda_medical_review_pmid>16492439</ivacaftor_fda_medical_review_pmid>
    <ivacaftor_fda_medical_review_pmid>9292910</ivacaftor_fda_medical_review_pmid>
    <ivacaftor_fda_medical_review_pmid>17761616</ivacaftor_fda_medical_review_pmid>
    <ivacaftor_fda_medical_review_pmid>8912731</ivacaftor_fda_medical_review_pmid>
    <ivacaftor_fda_medical_review_pmid>10516113</ivacaftor_fda_medical_review_pmid>
    <ivacaftor_fda_medical_review_pmid>9427882</ivacaftor_fda_medical_review_pmid>
    <ivacaftor_fda_medical_review_pmid>19447923</ivacaftor_fda_medical_review_pmid>
    <ivacaftor_fda_medical_review_pmid>16055882</ivacaftor_fda_medical_review_pmid>
    <ivacaftor_fda_medical_review_pmid>12838189</ivacaftor_fda_medical_review_pmid>
    <ivacaftor_fda_medical_review_pmid>11320950</ivacaftor_fda_medical_review_pmid>
    <ivacaftor_fda_medical_review_pmid>11106223</ivacaftor_fda_medical_review_pmid>
    <ivacaftor_fda_medical_review_pmid>7503821</ivacaftor_fda_medical_review_pmid>
    <ivacaftor_fda_other_pmid>19846789</ivacaftor_fda_other_pmid>
  </fda>
  <patent>
    <pl_USpatentno>US7495103</pl_USpatentno>
    <ivacaftor_npl_pmid>5637164 </ivacaftor_npl_pmid>
    <ivacaftor_npl_pmid>14980661</ivacaftor_npl_pmid>
    <ivacaftor_npl_pmid>15336384</ivacaftor_npl_pmid>
    <ivacaftor_npl_pmid>10841806 </ivacaftor_npl_pmid>
    <ivacaftor_npl_pmid>14505670 </ivacaftor_npl_pmid>
    <ivacaftor_npl_pmid>9014142</ivacaftor_npl_pmid>
    <ivacaftor_npl_pmid>12161441</ivacaftor_npl_pmid>
    <ivacaftor_npl_pmid>9014141</ivacaftor_npl_pmid>
  </patent>
  <ct>
    <ct_preapp_references_pmid>22047557</ct_preapp_references_pmid>
    <ct_preapp_publication_pmid>21083385</ct_preapp_publication_pmid>
    <ct_postapp_reference_pmid>25981758</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid>23952705</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid>8474788</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid>25981758</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid>27298017</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid>26568242</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid>25981758</ct_postapp_reference_pmid>
    <ct_postapp_reference_pmid>23952705</ct_postapp_reference_pmid>
    <ct_postapp_publication_pmid/>
  </ct>
  <pubmed>
    <pubmed_preapp_pmid>20301428</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>25473543</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>24855632</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>24461666</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>24461654</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>24429232</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>24429096</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>24429084</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>24328486</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>24309546</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>24298580</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>24298579</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>24289783</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>24282612</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>24258833</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>24119602</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>24095197</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>24084916</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>24081349</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>24066763</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>24048086</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>24039402</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>24030637</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>24004658</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>23992917</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>23964623</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>23952705</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>23923627</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>23922647</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>23891399</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>23856023</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>23818513</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>23788656</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>23757361</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>23757359</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>23757197</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>23664284</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>23657379</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>23652683</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>23628510</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>23616952</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>23616732</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>23590265</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>23574506</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>23457168</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>23457167</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>23457166</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>23440202</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>23409389</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>23313410</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>23302940</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>23276843</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>23276841</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>23199563</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>23027855</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22942289</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22914736</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22878883</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22768130</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22739718</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22723294</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22698459</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22688370</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22688363</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22618984</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22590787</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22543461</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22530244</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22508750</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22499233</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22407889</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22398597</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22395687</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22383668</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22323790</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22293084</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22266959</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22232540</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22047565</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>22047557</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21967060</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21724857</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21720393</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21654649</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21602569</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21475214</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21475213</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21349786</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21303308</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21083391</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>21083385</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>20829696</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>19846789</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>19747007</pubmed_preapp_pmid>
    <pubmed_preapp_pmid>19696677</pubmed_preapp_pmid>
    <pubmed_postapp_pmid>29048931</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>29046368</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>29045347</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>29042177</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>29040544</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>29037527</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>29035122</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>29032041</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>29020455</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28992608</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28989817</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28978522</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28953499</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28947035</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28930490</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28916704</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28891346</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28848893</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28846049</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28845852</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28836688</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28835336</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28787381</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28785019</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28769592</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28759146</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28711222</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28694231</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28667089</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28666755</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28651844</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28634110</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28611235</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28611092</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28606620</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28602538</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28592822</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28576305</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28554723</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28554721</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28539217</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28529073</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28477428</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28445004</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28419121</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28406713</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28371569</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28366727</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28362199</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28325531</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28314539</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28300821</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28245962</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28231890</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28222269</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28217196</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28190780</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28171547</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28143919</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>20301428</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28132845</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28107795</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28094839</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28087700</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28068001</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28042521</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28012258</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28011037</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27990075</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27976892</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27898234</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27895116</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27894875</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27875677</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27812499</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27810230</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27805836</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27804127</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27104944</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27792891</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27659740</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27773592</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27768743</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27745802</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27707539</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27703398</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27662106</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27660821</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27636560</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27626100</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27614011</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27585394</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27490265</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27482545</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27475719</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27475293</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27473897</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27469186</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27450143</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27441329</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27413118</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27402691</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27394157</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27393775</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27334259</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27328319</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27325384</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27324018</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27306167</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27298017</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27288484</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27288428</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27277131</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27258095</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27252987</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27248596</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27230445</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27226150</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27214033</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27185048</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27160424</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27158673</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27158420</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27150823</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27126691</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27097977</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27082186</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27081574</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27074519</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27035067</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27031658</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27030675</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27027688</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27017976</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27007499</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26996268</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26976279</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26975180</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26968770</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26968005</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26962591</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26944510</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26903594</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26894479</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26878157</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26848606</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26846474</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26840186</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26823621</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26823392</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26806675</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26803277</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26793709</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26749719</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26749716</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26744656</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26718821</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26698017</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26694805</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26677762</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26668427</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26581802</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26568242</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26567541</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26547591</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26545902</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26544137</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26510035</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26510034</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26506855</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26492939</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26488271</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26474553</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26417173</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26416827</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26410278</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26406363</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26403534</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26399136</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26390337</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26385858</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26371812</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26335956</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26324139</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26322933</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26303992</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26250833</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26245207</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26210165</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26209275</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26207804</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26182641</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26175480</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26170070</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26168933</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26137539</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26135562</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26132840</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26115565</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26097168</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26091951</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26078470</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26074007</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26073026</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26071414</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26070913</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26025260</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26018799</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26002404</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25990552</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25981758</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25971311</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25946147</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>28848841</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25853698</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25823699</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25820402</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25811419</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25769931</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25755212</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25732475</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25727661</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25707701</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25698453</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25688481</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25682022</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25660163</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25584290</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25574617</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27417354</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25514096</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25512598</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25487078</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25467948</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25466347</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25458465</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25447947</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25447681</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25441013</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25438972</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25425629</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25395018</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25384240</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25363320</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>27203051</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25330774</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25311995</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25270946</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25266997</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25266159</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25256050</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25251804</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25225552</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25182267</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25171465</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25171312</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25169789</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25148434</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25148205</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25145599</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25127305</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25103957</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25101887</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25101886</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25101884</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25099273</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25088968</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25083129</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25049054</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25037130</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>25025350</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>24997884</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>24973281</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>24973279</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>24970923</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>24934256</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>24932877</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>24927234</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>24902474</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>24832742</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>24832698</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>24796242</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>24791377</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>24771136</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>24660233</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>24656117</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>24618508</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>24598717</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>24532752</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>24528318</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>24523379</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>24522694</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>24520399</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>26556432</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>24309546</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>24258833</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>24251786</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>24114499</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>24106801</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>24095197</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>23992917</pubmed_postapp_pmid>
    <pubmed_postapp_pmid>23891399</pubmed_postapp_pmid>
    <pubmed_review_pmid>25584290</pubmed_review_pmid>
    <pubmed_review_pmid>25447947</pubmed_review_pmid>
    <pubmed_review_pmid>25395018</pubmed_review_pmid>
    <pubmed_review_pmid>25148205</pubmed_review_pmid>
    <pubmed_review_pmid>25037130</pubmed_review_pmid>
    <pubmed_review_pmid>24832698</pubmed_review_pmid>
    <pubmed_review_pmid>24791377</pubmed_review_pmid>
    <pubmed_review_pmid>24656117</pubmed_review_pmid>
    <pubmed_review_pmid>24114499</pubmed_review_pmid>
    <pubmed_review_pmid>24095197</pubmed_review_pmid>
    <pubmed_review_pmid>23992917</pubmed_review_pmid>
    <pubmed_ct_postapp_pmid>28611235</pubmed_ct_postapp_pmid>
    <pubmed_ct_postapp_pmid>28611092</pubmed_ct_postapp_pmid>
    <pubmed_ct_postapp_pmid>28143919</pubmed_ct_postapp_pmid>
    <pubmed_ct_postapp_pmid>28068001</pubmed_ct_postapp_pmid>
    <pubmed_ct_postapp_pmid>27805836</pubmed_ct_postapp_pmid>
    <pubmed_ct_postapp_pmid>27097977</pubmed_ct_postapp_pmid>
    <pubmed_ct_postapp_pmid>26803277</pubmed_ct_postapp_pmid>
    <pubmed_ct_postapp_pmid>26250833</pubmed_ct_postapp_pmid>
    <pubmed_ct_postapp_pmid>26135562</pubmed_ct_postapp_pmid>
    <pubmed_ct_postapp_pmid>26070913</pubmed_ct_postapp_pmid>
    <pubmed_ct_postapp_pmid>25981758</pubmed_ct_postapp_pmid>
    <pubmed_ct_postapp_pmid>25755212</pubmed_ct_postapp_pmid>
    <pubmed_ct_postapp_pmid>25682022</pubmed_ct_postapp_pmid>
    <pubmed_ct_postapp_pmid>25311995</pubmed_ct_postapp_pmid>
    <pubmed_ct_postapp_pmid>25266159</pubmed_ct_postapp_pmid>
    <pubmed_ct_postapp_pmid>25103957</pubmed_ct_postapp_pmid>
    <pubmed_ct_postapp_pmid>24973281</pubmed_ct_postapp_pmid>
    <pubmed_ct_postapp_pmid>24660233</pubmed_ct_postapp_pmid>
    <pubmed_ct_postapp_pmid>24461666</pubmed_ct_postapp_pmid>
    <pubmed_ct_postapp_pmid>23952705</pubmed_ct_postapp_pmid>
    <pubmed_ct_postapp_pmid>23922647</pubmed_ct_postapp_pmid>
    <pubmed_ct_postapp_pmid>23590265</pubmed_ct_postapp_pmid>
    <pubmed_ct_postapp_pmid>28611235</pubmed_ct_postapp_pmid>
    <pubmed_ct_postapp_pmid>28611092</pubmed_ct_postapp_pmid>
    <pubmed_ct_postapp_pmid>28143919</pubmed_ct_postapp_pmid>
    <pubmed_ct_postapp_pmid>28068001</pubmed_ct_postapp_pmid>
    <pubmed_ct_postapp_pmid>27805836</pubmed_ct_postapp_pmid>
    <pubmed_ct_postapp_pmid>27097977</pubmed_ct_postapp_pmid>
    <pubmed_ct_postapp_pmid>26803277</pubmed_ct_postapp_pmid>
    <pubmed_ct_postapp_pmid>26250833</pubmed_ct_postapp_pmid>
    <pubmed_ct_postapp_pmid>26135562</pubmed_ct_postapp_pmid>
    <pubmed_ct_postapp_pmid>26070913</pubmed_ct_postapp_pmid>
    <pubmed_ct_postapp_pmid>25981758</pubmed_ct_postapp_pmid>
    <pubmed_ct_postapp_pmid>25755212</pubmed_ct_postapp_pmid>
    <pubmed_ct_postapp_pmid>25682022</pubmed_ct_postapp_pmid>
    <pubmed_ct_postapp_pmid>25311995</pubmed_ct_postapp_pmid>
    <pubmed_ct_postapp_pmid>25266159</pubmed_ct_postapp_pmid>
    <pubmed_ct_postapp_pmid>25103957</pubmed_ct_postapp_pmid>
    <pubmed_ct_postapp_pmid>24973281</pubmed_ct_postapp_pmid>
    <pubmed_ct_postapp_pmid>24660233</pubmed_ct_postapp_pmid>
    <pubmed_ct_postapp_pmid>24461666</pubmed_ct_postapp_pmid>
    <pubmed_ct_postapp_pmid>23952705</pubmed_ct_postapp_pmid>
    <pubmed_ct_postapp_pmid>23922647</pubmed_ct_postapp_pmid>
    <pubmed_ct_postapp_pmid>23590265</pubmed_ct_postapp_pmid>
  </pubmed>
</drug>
